name: Tests-extended

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@v4

      - name: Enable corepack (for pnpm)
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run test runner (story store v7)
        run: |
          pnpm build
          pnpm test-storybook:ci

      - name: Run test runner (stories json mode)
        run: |
          pnpm build
          pnpm test-storybook:ci-json
