name: Typecheck

on: [push, pull_request]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable corepack (for pnpm)
        run: corepack enable

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: '20.x'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm exec tsc
